import Head from "next/head";
import { Container, Card, CardContent, Typography } from "@mui/material";
import LoginForm from "../../forms/LoginForm";

const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
  event.preventDefault();
  console.log("Submitted!");
};

export default function Login() {
  return (
    <div>
      <Head>
        <title>Receipt Tracker - Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container sx={{ justifyContent: "center", alignItems: "center" }}>
          <Card sx={{ minWidth: 275, padding: "2rem" }}>
            <CardContent>
              <Typography
                variant="h4"
                sx={{ fontWeight: "bold", textAlign: "center" }}
                gutterBottom
              >
                Sign In to Your Account
              </Typography>
              <LoginForm handleSubmit={handleSubmit} />
            </CardContent>
          </Card>
        </Container>
      </main>
    </div>
  );
}
