import Head from "next/head";
import { Container, Card, CardContent, Typography } from "@mui/material";
import CreateAccountForm from "../../forms/CreateAccountForm";

export default function CreateAccount() {
  return (
    <div>
      <Head>
        <title>Receipt Tracker - Create Account</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container sx={{ justifyContent: "center", alignItems: "center" }}>
          <Card sx={{ minWidth: 275, padding: "2rem" }}>
            <CardContent>
              <Typography
                variant="h4"
                sx={{ fontWeight: "bold", textAlign: "center" }}
                gutterBottom
              >
                Create an Account
              </Typography>
              <CreateAccountForm />
            </CardContent>
          </Card>
        </Container>
      </main>
    </div>
  );
}
