import Head from "next/head";
import Navbar from "./Navbar";
import Footer from "./Footer";
import styles from "../styles/Home.module.css";
import { useContext } from "react";
import { ColorModeContext } from "../pages/_app";

type LayoutProps = {
  children: React.ReactNode;
};

export default function Layout({ children }: LayoutProps) {
  const colorMode = useContext(ColorModeContext);
  return (
    <>
      <Head>
        <title>Receipt Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar toggleTheme={colorMode.toggleColorMode} />
      <main className={styles.main}>{children}</main>
      <Footer />
    </>
  );
}
