export const expenseOptions = [
    { value: 'food', label: 'Food' },
    { value: 'housing', label: 'Housing' },
    { value: 'transportation', label: 'Transportation' },
    { value: 'entertainment', label: 'Entertainment' },
    { value: 'education', label: 'Education' },
    { value: 'healthcare', label: 'Healthcare' },
    { value: 'utilities', label: 'Utilities' },
    { value: 'clothing', label: 'Clothing' },
    { value: 'phone', label: 'Phone' },
    { value: 'personal_care', label: 'Personal Care' },
    { value: 'pet_care', label: 'Pet Care' },
    { value: 'child_care', label: 'Child Care' },
    { value: 'memberships_and_subscriptions', label: 'Memberships and Subscriptions' },
    { value: 'gifts', label: 'Gifts' },
    { value: 'travel', label: 'Travel' },
    { value: 'debt_repayment', label: 'Debt Repayment' },
    { value: 'savings', label: 'Savings' },
    { value: 'investments', label: 'Investments' },
    { value: 'emergency_fund', label: 'Emergency Fund' },
    { value: 'large_purchases', label: 'Large Purchases' },
    { value: 'legal', label: 'Legal' },
    { value: 'taxes', label: 'Taxes' },
    { value: 'other', label: 'Other' },
];
