export const expenseOptions = [
    { value: 'FOOD', label: 'Food' },
    { value: 'HOUSING', label: 'Housing' },
    { value: 'TRANSPORTATION', label: 'Transportation' },
    { value: 'ENTERTAINMENT', label: 'Entertainment' },
    { value: 'EDUCATION', label: 'Education' },
    { value: 'HEALTHCARE', label: 'Healthcare' },
    { value: 'UTILITIES', label: 'Utilities' },
    { value: 'CLOTHING', label: 'Clothing' },
    { value: 'PHONE', label: 'Phone' },
    { value: 'PERSONAL_CARE', label: 'Personal Care' },
    { value: 'PET_CARE', label: 'Pet Care' },
    { value: 'CHILD_CARE', label: 'Child Care' },
    { value: 'MEMBERSHIPS_AND_SUBSCRIPTIONS', label: 'Memberships and Subscriptions' },
    { value: 'GIFTS', label: 'Gifts' },
    { value: 'TRAVEL', label: 'Travel' },
    { value: 'DEBT_REPAYMENT', label: 'Debt Repayment' },
    { value: 'SAVINGS', label: 'Savings' },
    { value: 'INVESTMENTS', label: 'Investments' },
    { value: 'EMERGENCY_FUND', label: 'Emergency Fund' },
    { value: 'LARGE_PURCHASES', label: 'Large Purchases' },
    { value: 'LEGAL', label: 'Legal' },
    { value: 'TAXES', label: 'Taxes' },
    { value: 'OTHER', label: 'Other' },
];
